version: "3.1"
services:
    www:
        build: .
        ports: 
            - 8001:80
        volumes:
            - www:/var/www/html
        depends_on:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: example 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on: 
            - db
        ports:
            - 8080:80
volumes:
    persistent:
